kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: routes-and-services-argocd
rules:
- apiGroups: ["", "route.openshift.io", "apps"]
  resources: ["routes", "services", "deployments", "imagestreams"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]