apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: db2
spec:
  description: |
    db2
  params:
  - name: repo-url
    type: string
    description: The git repository URL to clone from.
  workspaces:
  - name: shared-data
    description: |
      shared workspace
  tasks:
  - name: git-clone
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: master
  - name: deploy-db2
    taskRef:
      name: deploy-db2
    workspaces:
    - name: source
      workspace: shared-data
    runAfter: ["git-clone"] 