apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-frontend-dojo
  labels:
    app.kubernetes.io/version: "0.3"
  annotations:
    tekton.dev/pipelines.minVersion: "0.21.0"
    tekton.dev/displayName: "prep-frontend-dojo"
spec:
  description: >-
    deploy-frontend-dojo
  workspaces:
    - name: source
      description: shared workspace 
  params:
  - name: project-name
    description: project-name 
  steps:
    - name: deploy-frontend-dojo
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli
      script: |
        #!/bin/bash
        oc project $(params.project-name) > /dev/null 2>&1
        if [ $? != 0 ]; then 
          oc new-project $(params.project-name)
        fi

        cd $(workspaces.source.path)/frontend-dojo
        oc apply -f deployment/kubernetes.yaml
        oc expose svc/frontend-dojo
        echo "Done deploying frontend-dojo"

        ROUTE=$(oc get route frontend-dojo --template='{{ .spec.host }}')
        echo "http://${ROUTE}/CustomerOrderServicesWeb/"
