apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: smoke-test-prod
spec:
  steps:
    - name: smoke-test-prod
      image: ubi8/ubi-minimal
      script: |
        #!/bin/bash
        echo "Dummy only"
        echo "Smoke tests of core functionality should be done here"