apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: monolith-open-liberty-cloud-native
spec:
  description: |
    monolith-open-liberty-cloud-native
  params:
  - name: repo-url
    type: string
    description: The git repository URL to clone from.
  - name: project-name
    type: string
    description: The target project.
  workspaces:
  - name: shared-data
    description: |
      shared workspace
  tasks:
  - name: git-clone
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: master
  - name: wait-for-infrastructure
    taskRef:
      name: wait-for-infrastructure
    workspaces:
    - name: source
      workspace: shared-data
    runAfter: ["git-clone"] 
    params:
    - name: project-name
      value: $(params.project-name)
  - name: prep-monolith-open-liberty-cloud-native
    taskRef:
      name: prep-monolith-open-liberty-cloud-native
    workspaces:
    - name: source
      workspace: shared-data
    runAfter: ["wait-for-infrastructure"] 
    params:
    - name: project-name
      value: $(params.project-name)
  - name: buildah
    taskRef:
      name: buildah
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: IMAGE
      value: image-registry.openshift-image-registry.svc:5000/$(params.project-name)/build-monolith-open-liberty-cloud-native
    - name: CONTEXT
      value: $(workspaces.source.path)/monolith-open-liberty-cloud-native
    - name: TLSVERIFY
      value: "false"
    runAfter: ["prep-monolith-open-liberty-cloud-native"] 
  - name: deploy-monolith-open-liberty-cloud-native
    taskRef:
      name: deploy-monolith-open-liberty-cloud-native
    workspaces:
    - name: source
      workspace: shared-data
    runAfter: ["buildah"] 
    params:
    - name: project-name
      value: $(params.project-name)