apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: service-catalog-quarkus-reactive
spec:
  description: |
    service-catalog-quarkus-reactive
  params:
  - name: repo-url
    type: string
    description: The git repository URL to clone from.
  - name: project-name
    type: string
    description: The target project.
  workspaces:
  - name: shared-data
    description: |
      shared workspace
  tasks:
  - name: git-clone
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: master
  - name: wait-for-infra
    taskRef:
      name: wait-for-infrastructure
    workspaces:
    - name: source
      workspace: shared-data
    runAfter: ["git-clone"] 
    params:
    - name: project-name
      value: $(params.project-name)
  - name: configure
    taskRef:
      name: prep-service-catalog-quarkus-reactive
    workspaces:
    - name: source
      workspace: shared-data
    runAfter: ["wait-for-infra"] 
    params:
    - name: project-name
      value: $(params.project-name)
  - name: static-test
    taskRef:
      name: static-test
    runAfter: ["configure"]
  - name: build-and-unit-test
    taskRef:
      name: build-and-unit-test
    runAfter: ["static-test"]
  - name: build-and-push-image
    taskRef:
      name: buildah
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: IMAGE
      value: image-registry.openshift-image-registry.svc:5000/$(params.project-name)/build-service-catalog-quarkus-reactive
    - name: CONTEXT
      value: $(workspaces.source.path)/service-catalog-quarkus-reactive
    - name: TLSVERIFY
      value: "false"
    runAfter: ["build-and-unit-test"] 
  - name: deploy-in-dev
    taskRef:
      name: deploy-service-catalog-quarkus-reactive
    workspaces:
    - name: source
      workspace: shared-data
    runAfter: ["build-and-push-image"] 
    params:
    - name: project-name
      value: $(params.project-name)
  - name: smoke-test
    taskRef:
      name: smoke-test
    runAfter: ["deploy-in-dev"]
  - name: deploy-in-test
    taskRef:
      name: deploy-in-test
    runAfter: ["smoke-test"]
  - name: deploy-system-test
    taskRef:
      name: deploy-system-test
    runAfter: ["deploy-in-test"]
  - name: run-system-test
    taskRef:
      name: run-system-test
    runAfter: ["deploy-system-test"]
  - name: deploy-in-prod
    taskRef:
      name: deploy-in-prod
    runAfter: ["run-system-test"]
  - name: smoke-test-prod
    taskRef:
      name: smoke-test-prod
    runAfter: ["deploy-in-prod"]