version: '3.5'

networks:
  default:
    external:
      name: store-front-network

services:
    reverseproxy:
        image: proxy-nginx
        container_name: proxy-nginx
        ports:
            - 80:80
            - 443:443
        restart: always

    storefront-backend-open-native:
        image: storefront-backend-open-native
        container_name: storefront-backend-open-native
        restart: always
        environment:
          - CONTAINER=storefront-backend-open-native
        ports:
            - 9088:9088
            - 9445:9443

    storefront-frontend:
        image: storefront-frontend
        container_name: storefront-frontend
        restart: always
        environment:
          - CONTAINER=storefront-frontend
        ports:
            - 9081:9080
            - 9444:9443

    storefront-catalog:
        image: storefront-catalog
        container_name: storefront-catalog
        restart: always
        environment:
          - CONTAINER=storefront-catalog
        ports:
            - 9083:8082            