kind: Service
apiVersion: v1
metadata:
  name: frontend-dojo
  labels:
    app: frontend-dojo
spec:
  selector:
    app: frontend-dojo
  ports:
    - port: 9080
      name: http
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-dojo
  labels:
    app: frontend-dojo
spec:
  selector:
    matchLabels:
      app: frontend-dojo
  replicas: 1
  template:
    metadata: 
      labels:
        app: frontend-dojo
        version: v1
    spec:
      containers:
      - name: frontend-dojo
        image: image-registry.openshift-image-registry.svc:5000/app-mod-dev/build-frontend-dojo:latest
        ports:
        - containerPort: 9080
        livenessProbe:
          exec:
            command: ["sh", "-c", "curl -s http://localhost:9080/"]
          initialDelaySeconds: 20
        readinessProbe:
          exec:
            command: ["sh", "-c", "curl -s http://localhost:9080/"]
          initialDelaySeconds: 40
      restartPolicy: Always
---
