kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: storefront-db2
  namespace: 5b7aa5-dev
  labels:
    app: storefront-db2
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
  replicas: 1
  test: false
  selector:
    app: storefront-db2
    deploymentconfig: storefront-db2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: storefront-db2
        deploymentconfig: storefront-db2
    spec:
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: storefront-db2
          env:
            - name: DB2INST1_PASSWORD
              value: db2inst1
            - name: LICENSE
              value: accept
            - name: DBNAME
              value: orderdb
          securityContext:
            capabilities:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: true
          ports:
            - containerPort: 50000
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: image-registry.apps.silver.devops.gov.bc.ca/5b7aa5-tools/storefront-db2:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: mysvcacct
      serviceAccount: mysvcacct
      schedulerName: default-scheduler
