kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
 name: db2-scc
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: false
allowHostPID: false
allowHostPorts: true
allowPrivilegedContainer: false
allowedCapabilities:
- "SYS_RESOURCE"
- "IPC_OWNER"
- "SYS_NICE"
runAsUser:
 type: RunAsAny
seLinuxContext:
 type: MustRunAs
fsGroup:
 type: RunAsAny
supplementalGroups:
 type: RunAsAny