kind: Service
apiVersion: v1
metadata:
  name: monolith-open-liberty-cloud-native
  labels:
    app: monolith-open-liberty-cloud-native
spec:
  selector:
    app: monolith-open-liberty-cloud-native
  ports:
    - port: 9088
      name: http
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: monolith-open-liberty-cloud-native
  labels:
    app: monolith-open-liberty-cloud-native
spec:
  selector:
    matchLabels:
      app: monolith-open-liberty-cloud-native
  replicas: 1
  template:
    metadata: 
      labels:
        app: monolith-open-liberty-cloud-native
        version: v1
    spec:
      containers:
      - name: monolith-open-liberty-cloud-native
        image: image-registry.openshift-image-registry.svc:5000/app-mod-dev/build-monolith-open-liberty-cloud-native:latest
        ports:
        - containerPort: 9088
        livenessProbe:
          exec:
            command: ["sh", "-c", "curl -s http://localhost:9088/health/live"]
          initialDelaySeconds: 20
        readinessProbe:
          exec:
            command: ["sh", "-c", "curl -s http://localhost:9088/health/ready"]
          initialDelaySeconds: 40
      restartPolicy: Always
---
