apiVersion: v1
kind: ConfigMap
metadata:
  name: gas-config-properties
data:
  jvm.props: |-
    ResourceType=JavaVirtualMachine
    ImplementingResourceType=Server
    ResourceId=Cell=!{cellName}:Node=!{nodeName}:Server=!{serverName}:JavaProcessDef=:JavaVirtualMachine=
    AttributeInfo=jvmEntries
    initialHeapSize=2111

    # Header JVM System properties
    ResourceType=JavaVirtualMachine
    ImplementingResourceType=Server
    ResourceId=Cell=!{cellName}:Node=!{nodeName}:Server=!{serverName}:JavaProcessDef=:JavaVirtualMachine=
    AttributeInfo=systemProperties(name,value)
    #Properties
    gas.system.prop=hellaaaao

    #
    ResourceType=VirtualHost
    ImplementingResourceType=VirtualHost
    ResourceId=Cell=!{cellName}:VirtualHost=default_host
    AttributeInfo=aliases(port,hostname)
    #
    
    #
    #Properties
    #
    30713=*

    #
    ResourceType=VirtualHost
    ImplementingResourceType=VirtualHost
    ResourceId=Cell=!{cellName}:VirtualHost=admin_host
    AttributeInfo=aliases(port,hostname)
    #

    #
    #Properties
    #
    30717=*

